version: '3.3'

services:
  app:
    image: mytubefeed-app:latest
    ports:
      - "99:99"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/mytubefeed
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1G
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mytubefeed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/mongodb 